apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taskupdates.example.com
spec:
  group: example.com
  names:
    kind: TaskUpdate
    listKind: TaskUpdateList
    plural: taskupdates
    singular: taskupdate
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              completed:
                  type: integer
              task_id:
                  type: string
          status:
            type: object
