apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sparkrequests.example.com
spec:
  group: example.com
  names:
    kind: SparkRequest
    listKind: SparkRequestList
    plural: sparkrequests
    singular: sparkrequest
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              executorId:
                type: string
          status:
            type: object
