apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
rules:
- apiGroups:
  - ""  # Empty string represents the core API group
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - "example.com"  # Custom API group
  resources:
  - sparkjobs
  - sparkexecutors
  - sparkexecmsgs
  - taskupdates
  - sparkrequests
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
- kind: ServiceAccount
  name: spark
  namespace: default