apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypod-controller
  template:
    metadata:
      labels:
        app: mypod-controller
    spec:
      containers:
      - name: mypod-controller
        image: busybox
        command: ["./sync"]

